accordproject/techdocs

docs/cicero-tutorial_001.md
Proposing update to quickstart tutorial in order to clarify cicero-cli version and correct npm package, as suggested in https://github.com/accordproject/cicero/issues/50
=> docs(cicero-tutorial_001): Add "Install Cicero CLI" section

website/static/css/main.css
Fix for wrong hover on AP logo, to make it  consistent with  www.accordproject.org.
Remove styles with the same selectors, which overrides the proper one
closes #93
=> fix(styles): fix wrong opacity on hovering

README.md
Backs out change to add static image. Prepare for auto-generated image by the all-contributors bot
=> docs(README): Removes static contributors image

website/static/css/main.css
The sidebar nav menu for the docs has spacing issues
- Reduced side padding for the list elements
- Added a margin to stop the list elements from touching the scrollbar
Will look like this:
- Issue #116
=> Fix spacing issues in sidebar nav menu

website/core/Footer.js, website/pages/en/index.js
Change url for Slack button on main page from some google form, to https://accord-project-slack-signup.herokuapp.com/
Perhaps, that's not the end, and link in footer should also be changed 
closes #121 
P.S. if this change is not acceptable, or, not needed, feel free to close this PR and mark it with `invalid` label, just don't want to be a guy, who creates some spammy PRs to get a swag.
=> fix(main page): fix url in slack button - I121

docs/accordproject.md
- Fixed a typo where "lawyers" was capitalized for no reason
=> fix(docs): correct a typo

docs/markup-expr.md, docs/markup-variables-blocks.md
First draft of the `Variables and Blocks` and `Expressions` sections of the `Cicero Markup Guide`
- Adapt current information in issues for `v0.20` into documentation
- The inclusion of `Currently Unsupported` could possibly be removed
- Expressions feel like they could individually have more information, but unsure what to add
- Pull Request #147
=> feat(docs): init cicero markup guide - I87

website/static/css/main.css, website/static/img/Accord-Project-logo-small.svg
Signed-off-by: Sanket Shah <er.sanketshah@gmail.com>
Replacing the image (logo + text) to a smaller imager (logo) when the resolution is less than or equal to 480px
=> fix(website): change header logo to avoid search bar overlapping in smaller resolution

docs/markup-commonmark.md
Fixed formatting issues, following feedback from @mttrbrts @irmerk @jeromesimeon at the technology-wg call
- All code snippets now shown in code blocks 
- All 'rendered to' expressions shown in block quotes
As can be seen from the screenshot, in the `headings` subsection: 
(LEFT) `##h2` and `###h3` are in block quotes
(RIGHT) but they still appear in the side bar as actual headings. 
The same problem appeared in the `using underlines` subsection.
As this may cause confusion and hinder user navigation, I deleted block quotes completely for those two sub-sections, so that this problem does not occur (and the sidebar is clean). Please let me know if there is a way to fix this. 
- Issue #87 
- Pull Request #163
=> fixed formatting for markup-commonmark.md

CONTRIBUTING.md
Signed-off-by: Arshad Kazmi <arshadkazmi42@gmail.com>
This PR fixes the broken link of code of conduct in CONTRIBUTING.md file
- Change the old code of conduct url (`https://github.com/accordproject/docs/blob/master/Accord%20Project%20Code%20of%20Conduct.pdf`) to new url (`https://lfprojects.org/policies/code-of-conduct/`)
=> fix(CONTRIBUTING): broken coc link - I181

docs/tutorial-latedelivery.md
Signed-off-by: doomswatter <44559839+doomswatter@users.noreply.github.com>
Replaced link to old version of template with link to current version.
- Replaced link to old version of template with link to current version.
- 
- Issue #
=> fix(docs): correct link

docs/tutorial-nodejs.md
Signed-off-by: doomswatter <44559839+doomswatter@users.noreply.github.com>
Replaced broken link to Cicero API with correct one.
- Replaced broken link to Cicero API with correct one.
- 
- Issue #203
=> fix(docs): correct link - I203

docs/accordproject-concepts.md, docs/accordproject-developers.md, docs/accordproject-lawyers.md, docs/accordproject-laywers.md, docs/accordproject.md
- Updated `Introduction > Key Concepts`
- Expanded slightly on `Introduction > For Business `
- Changed the code images with code blocks
- Improved the explanations on `Introduction > Key Concepts` by elaborating on some of the concepts
- Fixed minor typos
For the `model` code block, the `cto` language is currently undefined, so I used `ergo` instead. Works perfectly fine, but may want to update this when concerto is supported in the future. 
- Issue #111 
- PR #207
=> Updated Introduction > Key Concepts

website/static/css/main.css
The upper left navbar elements in the main page for docs are a bit too close to each other, so I spaced them out a bit.
Original:
New:
- changed horizontal padding for 3 elements by 10px
=> style(css): increased spacing for navbar

docs/concerto-cli.md, website/i18n/en.json, website/sidebars.json
Added Concerto CLI documentation
Used some content from the `README.md` file from Concerto-cli:
https://github.com/accordproject/concerto/blob/master/packages/concerto-cli/README.md
Tried to match the format of `Cicero-cli` in the existing docs:
https://docs.accordproject.org/docs/cicero-cli.html 
- Format for code blocks unsure; left everything as `md` and kept everything white. let me know if you have any suggestions
- Cicero Issue #425
https://github.com/accordproject/cicero/issues/425#issuecomment-547419982
=> Added Concerto CLI documentation

docs/cicero-cli.md, docs/concerto-cli.md, docs/ergo-cli.md, docs/markup-cicero.md, website/i18n/en.json, website/sidebars.json
Updated `Cicero CLI` and `Ergo CLI`documentation for `0.20.0` release
- updated commands for the new `cicero-cli` and `ergo-cli` docs
- updated `markup-cicero` reflecting the changes @peterhunn made 
- changed `Legal-Tech Tutorials` to `Beginners Tutorials`
- in `ergo-cli`, `ergotop` section, `### Calling contracts`, everything from 
```
You can then invoke clauses of the contract:
```
doesn't seem to work on `0.20.0` release. 
- Issue #111 
- PR #231 #239 #240
=> Updated cicero-cli and ergo-cli for 0.20 release

docs/ref-logic.md
Signed-off-by: adrian <30812031+Ashiroq@users.noreply.github.com>
Introduces section on operator precedence to ergo reference.
- Added section on operator precedence
- Added table of precedence
Data pulled from: https://github.com/accordproject/ergo/blob/master/extraction/src/ErgoParser.mly#L193
If I missed anything let me know.
=> docs(reference): operator precedence (ergo#35)

docs/cicero-api.md, docs/concerto-api.md, website/scripts/build_api_md.sh, website/scripts/concerto-jsdoc.conf, website/versioned_docs/version-0.20/cicero-api.md, website/versioned_docs/version-0.20/concerto-api.md
- A bad glob expression in the script that builds the API docs from the source code meant that some files were not shown
Notably, the `Serializer` class was missing from the Concerto API reference
=> fix(api): Missing API docs for cicero and concerto

docs/cicero-cli.md
The changes introduced rename the subcommand `generate` as it longer exists. I think it has been replaced with `compile`.
- Renamed `generate` to `compile`.
- Please verify if my information about the typographical error is correct.
=> fix(cicero-cli): Rename subcommand for consistency with the CLI

docs/tutorial-latedelivery.md
Change type of `currencyCode` from `String` to codes given [here](https://models.accordproject.org/money.html). 
- Removed `" "` from `"USD"` to ensure correct type.
=> fix(tutorial-latedelivery): Fix type for assigning currencyCode

docs/model-properties.md
fixes #280 
- Change `not` to `no` in meta properties
=> docs(meta-properties.md): fix typo in description of default meta property

CONTRIBUTING.md, DEVELOPERS.md
Consolidates all non-repo-specific contribution guide documentation into `techdocs`
=> refactor(docs): consolidate contribution guides - I286

README.md, docs/ref-web-components.md, website/i18n/en.json, website/sidebars.json
Signed-off-by: Diana Lease <dianarlease@gmail.com>
- docs(*): update cicero-ui docs to be in line with web-components
- This updates the `next` version of the docs. Not sure how the `0.20` version gets generated or if I'm supposed to manually change those versioned files?
=> docs(*): update cicero-ui docs to be in line with web-components

docs/ref-concerto-decorators.md, website/i18n/en.json, website/sidebars.json, website/versioned_docs/version-0.21/model-decorators.md, website/versioned_docs/version-0.21/model-properties.md, website/versioned_docs/version-0.21/ref-concerto-decorators.md, website/versioned_sidebars/version-0.21-sidebars.json
- Move decorators documentation under concerto reference (rather than cicero reference)
- Retag/republish 0.21 version of the documentation
=> tag(0.21) Move decorators under concerto ref + republish 0.21

website/versioned_docs/version-0.21/logic-advanced-expr.md
- Fixes wrong link in Ergo "Template Literal" section
- Add new section for Ergo formatting using `as`
- Issue https://github.com/accordproject/cicero/issues/599
=> fix(ergo) Add documentation for Ergo 'as' expression

website/docusaurus.config.js, website/static/css/main.css
#335
I would like to merge these changes into the docusaurus-v2 branch and get some help if anyone else wants to contribute along side, as the css changes for the migration seems to be huge. I will continue and make smaller PRs as I make any progress.
Before:
https://docusaurus-v2--accordproject-docs.netlify.app/
After:
- Load the correct css file
- Fixed Header and Footer in Dark and Light Mode
- sticky banner
- front page needs a lot of css adjustments 
- navigation between pages, and through the sidebars
=> Docusaurus v2: Styling - PR1

DEVELOPERS.md
Extend docs on git(hub) guidelines
=> docs(DEVELOPERS): extend git context

docs/started-hello.md
The latest version of the Hello World template is 0.14.0, but 0.13.0 is used everywhere in the docs.
https://templates.accordproject.org/helloworld@0.14.0.html
- Updated template version from 0.13.0 to 0.14.0
None
None
=> Updated template version

website/pages/en/index.js, website/static/css/main.css
Signed-off-by: shubhangi013 <choudharyshubhangi13@gmail.com>
The PR aims at removing the underlining effect that causes a bad-user experience because of being uneven. 
- <ONE> added 'text-decoration: none!important;'
- Issue #381
=> fix(features): remove text-decoration on features

docs/ref-migrate-concerto-1.0-2.0.md, website/sidebars.json
- Adds a Concerto v1.x to v2.0 migration guide
=> Add Concerto v2 migration docs

docs/markup-commonmark.md
Signed-off-by: TC5022 <tanyac5022002@gmail.com>
Added documentation for tables in commonmark.
=> docs(commonmark.md): add docs for tables

docs/model-properties.md, website/versioned_docs/version-0.23.0/model-properties.md
We do not support the full ISO 8601 standard for `DateTime` values as advertised. We also support other formats that are not in ISO 8601.
Concerto in fact supports date and date-time formats that are in the intersection of the following specifications:
- ISO 8601
- RFC 3339
- HTML Living Standard.
See https://ijmacd.github.io/rfc3339-iso8601/ for a visualisation of the intersection.
Other formats outside of this intersection happen to be supported by DayJS. This behaviour is retained for backwards compatibility but is subject to change in future. Other platforms (such as .NET) should only commit to supporting the same subset as specified here.
Based on the recently extended test suite for JSON population (used in validation). This PR extends the documentation to be more specific about the …
=> docs(properties): clarify DateTime supported formats 

docs/accordproject-faq.md, docs/accordproject-tour.md, docs/accordproject.md, docs/ergo-tutorial.md, docs/example-eatapple.md, docs/logic-advanced-expr.md
- Fixed typos in docs directory
=> doc(docs): fix some typos
