accordproject/techdocs

website/package-lock.json, website/package.json
=> (fix) Docusaurus in dependencies

website/package-lock.json, website/package.json
=> (chore) Upgrade to Docusaurus 1.5

docs/accordproject-tools.md
change example ergo commands to use ergoc
Signed-off-by: Ryan (Chiungting) Lin <ryanctlin@hotmail.com>
=> docs: change ergo to ergoc

docs/cicero-tutorial_001.md
Addresses issue raised in https://github.com/accordproject/cicero/issues/248
=> Add network warning to Cicero Tutorial

website/i18n/en.json
=> (fix) Missing index

docs/cicero-tutorial.md
=> docs(cicero-tutorial): fix typo

docs/ergo-stdlib.md
=> (fix) Subtract mispelled

docs/advanced-latedelivery.md, website/versioned_docs/version-0.12.0/advanced-latedelivery.md
=> (fix) Minor edits to latedelivery tutorial

docs/accordproject.md, website/siteConfig.js, website/versioned_docs/version-0.12.0/accordproject.md
=> (fix) Tagline and description

docs/spec-concepts.md, docs/spec-overview.md, website/versioned_docs/version-0.12.0/spec-concepts.md, website/versioned_docs/version-0.12.0/spec-overview.md
=> (fix) Ergo official DSL for Accord Project

docs/ref-markup.md, website/versioned_docs/version-0.12.0/ref-markup.md
=> (fix) Add description for markup variables with enumerated types

website/pages/en/index.js
=> (fix) Wording for front page

website/core/Footer.js, website/i18n/en.json
=> (fix) Footer

CHARTER.md, README.md
- Initiate Linux Foundation charter as a markdown file.
- N/A
- N/A
=> docs(CHARTER): implement linux foundation charter - I62

README.md
Signed-off-by: Peter Hunn <peter@peterhunn.com>
=> docs(README): add trademark policy - I62

CONTRIBUTING.md
- Fixes links to DEVELOPERS.md page from CONTRIBUTORS.md page
=> docs(CONTRIBUTING): Fixes links to DEVELOPERS.md

README.md
Adding a Slack badge
- Added a Slack badge next to the Accord Project logo
- None
- None
=> docs(README): adds slack badge

docs/ref-logic-stdlib.md, website/versioned_docs/version-0.10.0/ergo-stdlib.md, website/versioned_docs/version-0.10.1.1/ergo-stdlib.md, website/versioned_docs/version-0.12.0/ref-logic-stdlib.md, website/versioned_docs/version-0.13.0/ref-logic-stdlib.md, website/versioned_docs/version-0.8.0.1/ergo-stdlib.md, website/versioned_docs/version-0.8.0/ergo-stdlib.md, website/versioned_docs/version-0.9.9/ergo-stdlib.md
=> Fixed namespace errors

docs/accordproject-installation.md
Just some edits in documentation
=> fix(docs): grammar changes 

docs/accordproject-resources.md, docs/cicero-api.md, docs/ergo-cli.md, docs/logic-ergo.md, docs/logic-simple-expr.md, docs/logic-stmt.md, docs/ref-logic-specification.md, docs/ref-markup.md
Signed-off-by: Alexey Pyltsyn <lex61rus@gmail.com>
=> fix(*): correct typos

README.md
Signed-off-by: DEBSUBHRO <debsubhro.roy10@yahoo.com>
Centering the logo of Accord Project.
- Signed off
- Issue #79 
- Pull Request #105
=> doc(README): centering logo of Accord Project

website/pages/en/index.js
Updated Alt text for images on the home page
- Added alt text to each image
- none
- Issue #113 
- Pull Request N/A
=> Updated alt text for images on the home page

README.md
Signed-off-by: Sumit Kharche <sumit.kharche@yahoo.in>
- added license badge
- None
=> docs(README): add license badge - I82

docs/example-eatapple.md
Removed unnecessary commas and changed verb forms
=> fix(docs): change for better readability

CONTRIBUTING.md, docs/advanced-latedelivery.md, docs/ergo-tutorial.md, docs/logic-simple-expr.md, docs/ref-logic.md, docs/ref-testing.md, docs/spec-packaging.md, website/versioned_docs/version-0.12.0/accordproject-resources.md, website/versioned_docs/version-0.12.0/ergo-tutorial.md, website/versioned_docs/version-0.12.0/logic-simple-expr.md, website/versioned_docs/version-0.12.0/logic-stmt.md, website/versioned_docs/version-0.12.0/ref-logic.md, website/versioned_docs/version-0.12.0/ref-testing.md, website/versioned_docs/version-0.12.0/spec-packaging.md, website/versioned_docs/version-0.12.3/advanced-latedelivery.md, website/versioned_docs/version-0.12.3/spec-packaging.md, website/versioned_docs/version-0.13.0/ergo-cli.md, website/versioned_docs/version-0.13.0/logic-stmt.md, website/versioned_docs/version-0.13.0/spec-packaging.md
=> fix(*): multiple typos

docs/markup-commonmark.md
First draft of the markup-commonmark.md
Included information on commonmark, with examples and explanations as necessary. 
- Not sure if some of these features are relevant in generating contract templates
- Not sure if this covers all the basic commonmark functionalities 
- Not sure if this is too similar to OpenLaw / Commonmark docs - should the sources be cited? If so, how? 
- Issue #111
=> Writing markup-commonmark.md

docs/advanced-latedelivery.md
=> fix(docs): correct typo mistakes

website/package-lock.json, website/package.json
Signed-off-by: Sanket Shah <er.sanketshah@gmail.com>
Update bump from `v 1.11.1` to `v 1.13.0` for Docusaurus package
=> fix(website): minor update bump for docusaurus package

DEVELOPERS.md
Signed-off-by: VishalS99 <s-vishal1999@hotmail.com>
Step to navigate to website directory 
- Added website navigation step in DEVELOPERS.md file
- Missed a step for Building a Project in DEVELOPERS.md
- Hacktoberfest
- Issue #156
=> fix(DEVELOPERS): add website navigation step - I156

docs/advanced-latedelivery.md
Replace buyer with seller
Work in progress, I'm working on images
=> fix(advanced-latedelivery): replace buyer with seller

docs/markup-variables-blocks.md
Update for code snippets in `Variables and Blocks`
- Utilize `volumediscountlist` for examples
N/A
- PR #147
- PR #148
=> fix(docs): correct json for cicero draft - I87

README.md
- <INSERT DESCRIPTION OF CHANGES>
- <SUB NOTES OF DESCRIPTIONS>
- <SUMMARIZE ALL COMMITS IN PULL REQUEST>
=> feat(docs): add ecosystem table - I80

docs/accordproject-resources.md
Signed-off-by: doomswatter <44559839+doomswatter@users.noreply.github.com>
Removed extra "on".
- Removed extra "on".
- 
- Issue #
=> docs: fix-typo

docs/0.13to0.20.md, docs/accordproject-studio.md, website/i18n/en.json, website/pages/en/index.js, website/sidebars.json
=> feature(0.20) Complete initial migration guide

website/core/Footer.js
Updated the URL for LF logo
- Changed the url from img/ to /img/
=> Updated the LF url

docs/ref-glossary.md, website/i18n/en.json, website/sidebars.json
Adding a new Glossary document under 'Reference Manuals'
Included a Glossary document under Reference Manuals to enlighten non-technical users
N/A. Anything related to information architecture.
=> Include a new 'Glossary' document

README.md
related to https://github.com/accordproject/techdocs/issues/80#issuecomment-544871864
=> fix(readme): fix broken link in ecosystem

docs/0.13to0.20.md
=> feature(0.20) Update migration guide for 0.20.0-beta.2

docs/0.13to0.20.md, docs/logic-complex-type.md, docs/logic-stmt.md, docs/started-hello.md, docs/started-installation.md
=> Minor fixes for 0.20

README.md
Fix closing tag
* fix a closing tag `<td>` -> `</td>`
* this was causing some weird rendering
=> fix(README): closing tag on ecosystem

docs/accordproject-concepts.md
Signed-off-by: Peter Hunn <code@peterhunn.com>
=> fix(docs): misc tidy-up

website/static/css/main.css
Changed style of hyperlinks
- Green color is now default for all the hyperlinks
- Underline text is now default for all the hyperlinks
- Please check if this is what you want
=> Added style hyperlinks

README.md
Fix readme typo
- fix-readme-typo
=> fix(README): typo - I237

website/static/css/main.css
Code text have now higher contrast
- Changed code text color from `inherit` to `#15203C`
=> Code text with higher contrast

website/pages/en/index.js
fix(pages/en/index): fix italic and bold styling
Signed-off-by: Diana Lease <dianarlease@gmail.com>
=> fix(pages/en/index): fix italic and bold styling

docs/accordproject-concepts.md, docs/accordproject.md, docs/ref-glossary.md, docs/started-hello.md, docs/started-installation.md, docs/tutorial-create.md, docs/tutorial-latedelivery.md, docs/tutorial-library.md, website/sidebars.json
Proofread Introduction, Getting Started and User Tutorial sections
=> docs(0.20): Proofread Introduction, Getting Started and User Tutorials

docs/markup-cicero.md, docs/markup-variables.md, docs/model-enums.md, docs/model-properties.md, docs/model-relationships.md, docs/ref-migrate-0.13-0.20.md
Proofreading through new additions to docs
- Swapped some formatting around to be more clear
- Editing formatting
- Switched out enum gender example for cards
N/A
N/A
=> fix(docs): formatting and grammar

docs/logic-advanced-expr.md, docs/logic-complex-type.md, docs/logic-decl.md, docs/logic-module.md, docs/logic-simple-type.md, docs/logic-stmt.md, docs/ref-logic-stdlib.md, website/i18n/en.json, website/versioned_docs/version-0.20.0/accordproject.md, website/versioned_docs/version-0.20.0/logic-advanced-expr.md, website/versioned_docs/version-0.20.0/logic-complex-type.md, website/versioned_docs/version-0.20.0/logic-decl.md, website/versioned_docs/version-0.20.0/logic-module.md, website/versioned_docs/version-0.20.0/logic-simple-type.md, website/versioned_docs/version-0.20.0/logic-stmt.md, website/versioned_docs/version-0.20.0/markup-blocks.md, website/versioned_docs/version-0.20.0/markup-cicero.md, website/versioned_docs/version-0.20.0/markup-variables.md, website/versioned_docs/version-0.20.0/model-enums.md, website/versioned_docs/version-0.20.0/model-properties.md, website/versioned_docs/version-0.20.0/model-relationships.md, website/versioned_docs/version-0.20.0/ref-logic-stdlib.md, website/versioned_docs/version-0.20.0/ref-logic.md, website/versioned_docs/version-0.20.0/ref-migrate-0.13-0.20.md, website/versioned_docs/version-0.20.0/tutorial-templates.md
- Fixes to Ergo Guide
- Add missing Ergo Stdlib functions from `0.20`
- Publishes fixes from @4katie and @irmerk to `0.20.0`
=> Various Improvements to 0.20

docs/ergo-repl.md, website/i18n/en.json
=> fix(repl) Corrections to Ergo REPL documentation

docs/ref-migrate-0.13-0.20.md, website/versioned_docs/version-0.20.2/ref-migrate-0.13-0.20.md
=> fix(migration) change a title

docs/cicero-cli.md, docs/concerto-cli.md, docs/ergo-cli.md, docs/ergo-tutorial.md, docs/markus-cli.md, docs/model-api.md, docs/started-installation.md, docs/tutorial-create.md, website/i18n/en.json, website/versioned_docs/version-0.12/ergo-cli.md, website/versioned_docs/version-0.12/ergo-tutorial.md, website/versioned_docs/version-0.13/accordproject-installation.md, website/versioned_docs/version-0.13/basic-create.md, website/versioned_docs/version-0.13/basic-use.md, website/versioned_docs/version-0.13/ergo-cli.md, website/versioned_docs/version-0.13/ergo-tutorial.md, website/versioned_docs/version-0.20/cicero-cli.md, website/versioned_docs/version-0.20/concerto-cli.md, website/versioned_docs/version-0.20/ergo-cli.md, website/versioned_docs/version-0.20/markus-cli.md, website/versioned_docs/version-0.20/model-api.md, website/versioned_docs/version-0.20/started-installation.md, website/versioned_docs/version-0.20/tutorial-create.md
This adjusts each versions of the documentation so the `npm install` commands have the correct version number.
=> fix(versions) Now each version of the docs has correct npm install

website/versioned_docs/version-0.20/ref-cicero-ui.md, website/versioned_sidebars/version-0.20-sidebars.json
=> chore(0.20) Publish Cicero UI reference page to 0.20

docs/ref-cicero-ui.md, website/i18n/en.json, website/versioned_docs/version-0.20/ref-cicero-ui.md
=> fix(UI) Accurate 'non supported' list in editor

docs/markup-blocks.md, website/versioned_docs/version-0.20/markup-blocks.md
=> fix(ciceromark) Document else branch for conditional blocks

docs/tutorial-latedelivery.md, website/static/css/main.css
Signed-off-by: Shrey Sachdeva <shreysachdeva.2000@gmail.com>
Improve contrast ratio of docs text.
- Updated CSS
- Removed additional CSS overriding existing body color.
- Fix typo in docs
- N/A
- Issue #57 in cicero-ui
=> style(docs): change text color for minimum contrast accessibility - I268

website/core/Footer.js, website/i18n/en.json
=> feature(footer) Add link to Vimeo recordings

docs/tutorial-create.md
Signed-off-by: Brethland <ycy1207694344@gmail.com>
fix a typo in Template Creation section.
- Issue #272
=> fix(docs) : fix a typo in create section - I272

docs/model-api.md
fixed #282 
- Remove npm version of `concerto-core`
=> docs(model-api): Remove concerto-cli npm version - I282

README.md
=> docs(README): add tsc email

website/versioned_docs/version-0.20/concerto-cli.md
- <INSERT DESCRIPTION OF CHANGES>
- <SUB NOTES OF DESCRIPTIONS>
- <SUMMARIZE ALL COMMITS IN PULL REQUEST>
=> docs(concerto-cli):change directory name from "models" to "model"

docs/concerto-cli.md, website/versioned_docs/version-0.20/concerto-cli.md
- <INSERT DESCRIPTION OF CHANGES>
- <SUB NOTES OF DESCRIPTIONS>
- <SUMMARIZE ALL COMMITS IN PULL REQUEST>
=> docs(concerto-cli):substitute "--format" with "--target"

docs/accordproject-business.md, docs/accordproject-developers.md, docs/accordproject-faq.md, docs/accordproject-lawyers.md, docs/accordproject.md, website/i18n/en.json, website/sidebars.json
- <INSERT DESCRIPTION OF CHANGES>
- <SUB NOTES OF DESCRIPTIONS>
- <SUMMARIZE ALL COMMITS IN PULL REQUEST>
=> feat(intro): init faq - I297

docs/ref-markus-cli.md, website/versioned_docs/version-0.21/ref-markus-cli.md
=> fix(typo) roundtriP

.github/pull_request_template.md, README.md
- Change PR template to point to closing an issue
- Remove all contributors to `README`
- Update `markdown-transform` ecosystem
- N/A
=> docs(README): cleanup ecosystem table

docs/model-decorators.md, docs/model-properties.md, docs/ref-decorators.md, website/i18n/en.json, website/sidebars.json
Signed-off-by: Dan Selman <danscode@selman.org>
Document the AP decorators.
=> docs(decorators) : add documentation for the AP decorators

docs/markup-templatemark.md, website/versioned_docs/version-0.21/markup-templatemark.md
- Add section to TemplateMark guide on formatting amounts
=> fix(templatemark) Add documentation for amounts formatting

docs/ref-ergo-stdlib.md, website/i18n/en.json, website/versioned_docs/version-0.21/ref-ergo-stdlib.md
- Update to Ergo stdlib reference documentation
=> fix(ergo) Update Ergo Stdlib reference

website/siteConfig.js
Signed-off-by: Martin Halford <martin@benext.io>
Added "REIV SmartVicForms" and "beNEXT" to list of `users`.
=> Added 'REIV SmartVicForms' and 'beNEXT'

docs/ref-migrate-0.13-0.20.md, docs/ref-migrate-0.20-0.21.md, docs/ref-migrate-concerto-0.82-1.0.md, website/sidebars.json
Signed-off-by: Dan Selman <danscode@selman.org>
Concerto v0.82 to v1.0 migration documentation
=> feat (concerto) : document v1 migration

docs/model-concerto.md
=> (fix) Broken link in model-concerto.md

docs/accordproject-template.md, docs/logic-ergo.md
- Updated Hyperlink and its text
=> fix(docs): update broken links 

website/versioned_docs/version-0.21/accordproject-faq.md, website/versioned_docs/version-0.21/accordproject-slc.md, website/versioned_docs/version-0.21/accordproject-template.md, website/versioned_docs/version-0.21/logic-complex-type.md, website/versioned_docs/version-0.21/logic-ergo.md, website/versioned_docs/version-0.21/logic-simple-expr.md, website/versioned_docs/version-0.21/markup-templatemark.md, website/versioned_docs/version-0.21/model-concerto.md, website/versioned_docs/version-0.21/model-decorators.md, website/versioned_docs/version-0.21/ref-cicero-testing.md, website/versioned_docs/version-0.21/ref-ergo-cli.md, website/versioned_docs/version-0.21/ref-markus-cli.md, website/versioned_docs/version-0.21/ref-migrate-0.13-0.20.md, website/versioned_docs/version-0.21/ref-migrate-0.20-0.21.md, website/versioned_docs/version-0.21/ref-migrate-concerto-0.82-1.0.md, website/versioned_docs/version-0.21/started-hello.md, website/versioned_docs/version-0.21/started-resources.md, website/versioned_docs/version-0.21/tutorial-nodejs.md, website/versioned_sidebars/version-0.21-sidebars.json
- Fixes typo in Ergo optionals guide
- Refreshes version 0.21, publishes numerous previous fixes
=> chore(*) Refresh version 0.21 + fix typo in Ergo optionals

website/i18n/en.json, website/versioned_docs/version-0.22/ref-cicero-cli.md, website/versioned_docs/version-0.22/ref-concerto-cli.md, website/versioned_docs/version-0.22/ref-ergo-cli.md
- Update CLI documentation for `0.22`
=> feature(cli) Upgrade CLI documentation for 0.22

docs/ref-concerto-api.md, website/package-lock.json, website/versioned_docs/version-0.22/ref-concerto-api.md
Signed-off-by: jeromesimeon <jeromesimeon@me.com>
- Update Concerto API documentation, based on latest changes in Concerto `1.0.3`
=> chore(api) Update Concerto API documentation

docs/markup-preliminaries.md
Signed-off-by: aman <amanvivoy51l@gmail.com>
- Change in TemplateGuides/preliminaries- changed blockBane to blockName
- Issue #391
=> docs(TemplateGuides):correct typo in TemplateGuides - #391

docs/tutorial-nodejs.md, website/versioned_docs/version-0.22/tutorial-nodejs.md
Signed-off-by: Matt Roberts <code@rbrts.uk>
- Updates the Node.js Tutorial to use the latest Cicero 0.22 API
=> fix(tutorial): update nodejs tutorial for 0.22

docs/model-vocabulary.md, docs/ref-concerto-api.md, website/i18n/en.json, website/package-lock.json, website/package.json, website/scripts/build_api_md.sh, website/scripts/concerto-jsdoc.conf, website/sidebars.json
Signed-off-by: Dan Selman <danscode@selman.org>
Update JSDoc to markdown library
Regenerate the JSDoc to include the new packages
Added basic documentation for the `concerto-vocabulary` package.
=> feat: add docs for vocabulary

docs/accordproject.md
Signed-off-by: Jeevan Kiran Lenka <prateeklenka286@gmail.com>
- <ONE> Fixes  `previous link` [Join our Community](https://www.accordproject.org/membership/) into `new link` [Join our Community](https://discord.com/invite/Zm99SKhhtA) under `For Devlopers` , and `For Layers` section in https://github.com/accordproject/techdocs/blob/master/docs/accordproject.md
=> docs(accordproject.md): fix join our community link

docs/model-properties.md
Signed-off-by: Jerome Simeon <Jerome.Simeon@docusign.com>
- Some fixes to range documentation for numeric value in models
=> fix(model) Some improvements to documentation for range on numeric values

DEVELOPERS.md
Add the link to the commit message conventions of the Accord project.
- Add the link to the commit message conventions of the Accord project.
- Issue #423
=> Add: commit message conventions to DEVELOPERS.md

DEVELOPERS.md
- link fixed
- Issue #424 
- Pull Request #426
=> doc(dev): updated DEVELOPERS.md
